import { StyleSheet } from 'react-native';

export const contestStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    padding: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginTop: 50,
    marginBottom: 20,
    color: '#333',
    textAlign: 'center',
    fontFamily: 'Gudea-Bold',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    color: '#5D3FD3',
    fontSize: 16,
    fontFamily: 'Gudea-Regular',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    marginTop: 10,
    color: '#ff6b6b',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Gudea-Regular',
  },
  retryButton: {
    backgroundColor: '#5D3FD3',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  retryButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontFamily: 'Gudea-Bold',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    marginTop: 10,
    color: '#555',
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Gudea-Regular',
  },
  listContainer: {
    paddingBottom: 100, // Add padding to account for bottom navigation
  },
  contestCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    marginBottom: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(236, 236, 246, 0.9)',
  },
  contestBadge: {
    position: 'absolute',
    top: -10,
    right: 20,
    backgroundColor: '#5D3FD3',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  contestType: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'Gudea-Bold',
  },
  contestName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 8,
    marginBottom: 16,
    fontFamily: 'Gudea-Bold',
    lineHeight: 24,
  },
  timeInfoContainer: {
    backgroundColor: 'rgba(245, 245, 255, 0.9)',
    borderRadius: 12,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(230, 230, 250, 0.9)',
  },
  timeInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  timeInfoText: {
    marginLeft: 8,
    color: '#444',
    fontSize: 14,
    fontFamily: 'Gudea-Regular',
  },
  divider: {
    width: 1,
    backgroundColor: 'rgba(93, 63, 211, 0.2)',
    marginHorizontal: 10,
  },
  countdownContainer: {
    backgroundColor: 'rgba(93, 63, 211, 0.9)',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  countdownText: {
    color: 'white',
    marginLeft: 10,
    fontSize: 15,
    fontWeight: 'bold',
    fontFamily: 'Gudea-Bold',
  },
});
